// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf2O7b1baVs_v12cOYJeauDQn-0mkhNuk',
    appId: '1:490725560666:web:a49fedf862a527572a2363',
    messagingSenderId: '490725560666',
    projectId: 'smart-cat-water-bowl',
    authDomain: 'smart-cat-water-bowl.firebaseapp.com',
    storageBucket: 'smart-cat-water-bowl.firebasestorage.app',
    measurementId: 'G-GSCENGEZGR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqesnXLsTdaMhhnMiPDb8wJnB5shltVyM',
    appId: '1:490725560666:android:dff44d8dcc73731f2a2363',
    messagingSenderId: '490725560666',
    projectId: 'smart-cat-water-bowl',
    storageBucket: 'smart-cat-water-bowl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrC7-vAuQoBr_b-WMf-w1NVcY5ZQscfsU',
    appId: '1:490725560666:ios:f25793ab75eea3bc2a2363',
    messagingSenderId: '490725560666',
    projectId: 'smart-cat-water-bowl',
    storageBucket: 'smart-cat-water-bowl.firebasestorage.app',
    iosBundleId: 'com.example.smartCatWaterBowl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrC7-vAuQoBr_b-WMf-w1NVcY5ZQscfsU',
    appId: '1:490725560666:ios:f25793ab75eea3bc2a2363',
    messagingSenderId: '490725560666',
    projectId: 'smart-cat-water-bowl',
    storageBucket: 'smart-cat-water-bowl.firebasestorage.app',
    iosBundleId: 'com.example.smartCatWaterBowl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAf2O7b1baVs_v12cOYJeauDQn-0mkhNuk',
    appId: '1:490725560666:web:30f7427200f1c6cc2a2363',
    messagingSenderId: '490725560666',
    projectId: 'smart-cat-water-bowl',
    authDomain: 'smart-cat-water-bowl.firebaseapp.com',
    storageBucket: 'smart-cat-water-bowl.firebasestorage.app',
    measurementId: 'G-2NXFGKQ7ZM',
  );
}
